name: Publish to pub.dev

on:
  workflow_run:
    workflows: ["Deploy Demo"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      id-token: write # Required for authentication using OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: dart analyze

      - name: Publish to pub.dev
        run: dart pub publish
